GET http://localhost:8080/clients
Accept: application/json

###

GET http://localhost:8080/clients/1

###
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "email": "test@test",
    "phoneNumber": "55555555"
}